Project Title: Cars93 Data Analysis Using Python

Project Domain: Data Analytics

Project Overview: Cars93 Data Analysis is a data analytics project that focuses on analyzing car specifications using Python. The project explores car prices, horsepower, mileage, engine size, and other features to identify patterns and compare vehicle performance.

## Skills Used

- Python Programming
- Data Cleaning and Preprocessing
- Pandas
- NumPy
- Exploratory Data Analysis (EDA)
- Data Visualization
- Matplotlib
- Seaborn
- Data Analysis and Interpretation
- Business Insights Generation

Step 1: Data loading & Understanding

In [ ]:
import pandas as pd
import numpy as np


df = pd.read_csv('/content/Cars93.csv')
df.head()

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [ ]:
print(df.shape)
print(df.columns)
df.info()

(93, 28)
Index(['id', 'Manufacturer', 'Model', 'Type', 'Min.Price', 'Price',
       'Max.Price', 'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain',
       'Cylinders', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile',
       'Man.trans.avail', 'Fuel.tank.capacity', 'Passengers', 'Length',
       'Wheelbase', 'Width', 'Turn.circle', 'Rear.seat.room', 'Luggage.room',
       'Weight', 'Origin', 'Make'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  93 non-null     int64
 1   Manufacturer        93 non-null     object
 2   Model               93 non-null     object
 3   Type                93 non-null     object
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64
 8   MPG.highway         93 non-null     int64
 9   AirBags             56 non-null     object
 10  DriveTrain          93 non-null     object
 11  Cylinders           93 non-null     object
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64
 14  RPM                 93 non-null     int64
 15  Rev.per.mile        93 non-null     int64
 16  Man.trans.avail     93 non-null     object
 17  Fuel.tank.capacity  93 non-null     float64
 18  Passengers          93 non-null     int64
 19  Length              93 non-null     int64
 20  Wheelbase           93 non-null     int64
 21  Width               93 non-null     int64
 22  Turn.circle         93 non-null     int64
 23  Rear.seat.room      91 non-null     float64
 24  Luggage.room        82 non-null     float64
 25  Weight              93 non-null     int64
 26  Origin              93 non-null     object
 27  Make                93 non-null     object
dtypes: float64(7), int64(12), object(9)
memory usage: 20.5+ KB

Step 2: Data Cleaning & Preprocessing

In [ ]:
# Check dataset size
print("Dataset Shape:", df.shape)

# Display column names
print("\nColumn Names:")
print(df.columns.tolist())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Check duplicate records
print("\nDuplicate Records:", df.duplicated().sum())

Dataset Shape: (93, 28)

Column Names:
['id', 'Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price', 'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail', 'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width', 'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin', 'Make']

Missing Values:
id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

Duplicate Records: 0

 Step:4 Missing Values Treatment

In [ ]:
print(df.isnull().sum())

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

Step 3: Data Formatting and Type Conversion

In [ ]:

# Step 3: Data Formatting and Type Conversion

import pandas as pd
import numpy as np

# Check data types before conversion
print("Before Conversion:")
print(df.dtypes)

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Convert numeric columns
numeric_columns = [
    'Price', 'MPG.city', 'MPG.highway',
    'EngineSize', 'Horsepower', 'RPM',
    'Rev.per.mile', 'Fuel.tank.capacity',
    'Passengers', 'Length', 'Wheelbase', 'Width', 'Weight'
]

for col in numeric_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Clean text columns
for col in df.select_dtypes(include=['object', 'string']).columns:
    df[col] = df[col].astype('string').str.strip()

# Check data types after conversion
print("\nAfter Conversion:")
print(df.dtypes)

print("\nCars93 data formatting completed successfully!")

# Display first five rows
display(df.head())

Before Conversion:
id                      int64
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city                int64
MPG.highway             int64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower              int64
RPM                     int64
Rev.per.mile            int64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers              int64
Length                  int64
Wheelbase               int64
Width                   int64
Turn.circle             int64
Rear.seat.room        float64
Luggage.room          float64
Weight                  int64
Origin                 object
Make                   object
dtype: object

After Conversion:
id                             int64
Manufacturer          string[python]
Model                 string[python]
Type                  string[python]
Min.Price                    float64
Price                        float64
Max.Price                    float64
MPG.city                       int64
MPG.highway                    int64
AirBags               string[python]
DriveTrain            string[python]
Cylinders             string[python]
EngineSize                   float64
Horsepower                     int64
RPM                            int64
Rev.per.mile                   int64
Man.trans.avail       string[python]
Fuel.tank.capacity           float64
Passengers                     int64
Length                         int64
Wheelbase                      int64
Width                          int64
Turn.circle                    int64
Rear.seat.room               float64
Luggage.room                 float64
Weight                         int64
Origin                string[python]
Make                  string[python]
dtype: object

Cars93 data formatting completed successfully!

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,<NA>,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,<NA>,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [ ]:
df.dtypes

id                             int64
Manufacturer          string[python]
Model                 string[python]
Type                  string[python]
Min.Price                    float64
Price                        float64
Max.Price                    float64
MPG.city                       int64
MPG.highway                    int64
AirBags               string[python]
DriveTrain            string[python]
Cylinders             string[python]
EngineSize                   float64
Horsepower                     int64
RPM                            int64
Rev.per.mile                   int64
Man.trans.avail       string[python]
Fuel.tank.capacity           float64
Passengers                     int64
Length                         int64
Wheelbase                      int64
Width                          int64
Turn.circle                    int64
Rear.seat.room               float64
Luggage.room                 float64
Weight                         int64
Origin                string[python]
Make                  string[python]
dtype: object

In [ ]:
df.isnull().sum()

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

Step 5: EDA – Data Analysis

In [ ]:



import pandas as pd
import numpy as np

# Display first five records
print("First 5 Records:")
display(df.head())

# Display dataset shape
print("\nDataset Shape:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# Display column names
print("\nColumn Names:")
print(df.columns.tolist())

# Statistical summary
print("\nStatistical Summary:")
display(df.describe())

# Check unique car manufacturers
if 'Manufacturer' in df.columns:
    print("\nNumber of Manufacturers:")
    print(df['Manufacturer'].nunique())

# Average price
if 'Price' in df.columns:
    print("\nAverage Car Price:")
    print(round(df['Price'].mean(), 2))

# Highest horsepower
if 'Horsepower' in df.columns:
    print("\nMaximum Horsepower:")
    print(df['Horsepower'].max())

# Average city mileage
if 'MPG.city' in df.columns:
    print("\nAverage City Mileage:")
    print(round(df['MPG.city'].mean(), 2))

print("\nEDA completed successfully!")

First 5 Records:

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,<NA>,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,<NA>,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

Dataset Shape:
Rows: 93
Columns: 28

Column Names:
['id', 'Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price', 'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail', 'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width', 'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin', 'Make']

Statistical Summary:

,id,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000,93.000000
mean,47.000000,17.125806,19.509677,21.898925,22.365591,29.086022,2.667742,143.827957,5280.645161,2332.204301,16.664516,5.086022,183.204301,103.946237,69.376344,38.956989,27.829670,13.890244,3072.903226
std,26.990739,8.746029,9.659430,11.030457,5.619812,5.331726,1.037363,52.374410,596.731690,496.506525,3.279370,1.038979,14.602382,6.819674,3.778986,3.223265,2.989072,2.997967,589.896510
min,1.000000,6.700000,7.400000,7.900000,15.000000,20.000000,1.000000,55.000000,3800.000000,1320.000000,9.200000,2.000000,141.000000,90.000000,60.000000,32.000000,19.000000,6.000000,1695.000000
25%,24.000000,10.800000,12.200000,14.700000,18.000000,26.000000,1.800000,103.000000,4800.000000,1985.000000,14.500000,4.000000,174.000000,98.000000,67.000000,37.000000,26.000000,12.000000,2620.000000
50%,47.000000,14.700000,17.700000,19.600000,21.000000,28.000000,2.400000,140.000000,5200.000000,2340.000000,16.400000,5.000000,183.000000,103.000000,69.000000,39.000000,27.500000,14.000000,3040.000000
75%,70.000000,20.300000,23.300000,25.300000,25.000000,31.000000,3.300000,170.000000,5750.000000,2565.000000,18.800000,6.000000,192.000000,110.000000,72.000000,41.000000,30.000000,15.000000,3525.000000
max,93.000000,45.400000,61.900000,80.000000,46.000000,50.000000,5.700000,300.000000,6500.000000,3755.000000,27.000000,8.000000,219.000000,119.000000,78.000000,45.000000,36.000000,22.000000,4105.000000

Number of Manufacturers:
32

Average Car Price:
19.51

Maximum Horsepower:
300

Average City Mileage:
22.37

EDA completed successfully!

Q1. What is the average price of cars?

In [ ]:
print("Average Car Price:", round(df['Price'].mean(), 2))

Average Car Price: 19.51

Q2. Which car has the highest price?

In [ ]:
highest_price_car = df.loc[df['Price'].idxmax()]
print(highest_price_car)

id                                    59
Manufacturer               Mercedes-Benz
Model                               300E
Type                             Midsize
Min.Price                           43.8
Price                               61.9
Max.Price                           80.0
MPG.city                              19
MPG.highway                           25
AirBags               Driver & Passenger
DriveTrain                          Rear
Cylinders                              6
EngineSize                           3.2
Horsepower                           217
RPM                                 5500
Rev.per.mile                        2220
Man.trans.avail                       No
Fuel.tank.capacity                  18.5
Passengers                             5
Length                               187
Wheelbase                            110
Width                                 69
Turn.circle                           37
Rear.seat.room                      27.0
Luggage.room                        15.0
Weight                              3525
Origin                           non-USA
Make                  Mercedes-Benz 300E
Name: 58, dtype: object

Q3. Which car has the highest horsepower?

In [ ]:
highest_hp_car = df.loc[df['Horsepower'].idxmax()]
print(highest_hp_car)

Q4. What is the average city mileage?

In [ ]:
print("Average City Mileage:", round(df['MPG.city'].mean(), 2))

Average City Mileage: 22.37

Q5. What is the average highway mileage?

In [ ]:
print("Average Highway Mileage:", round(df['MPG.highway'].mean(), 2))

Average Highway Mileage: 29.09

In [ ]:
!jupyter nbconvert --to html ""